### ISSUE TITLE
Page transition slow

### ISSUE THREAD

**Issue by alansouzati** [styled-components/styled-components-website#58] opened 2017-07-13 22:44 UTC
When I'm clicking in "Basics" or "Advanced" it is taking a while before I see the page content.

https://media.giphy.com/media/xDPuIsXoRWxKo/giphy.gif

This could be related to #36

**Comment by philpl** [comment] 2017-07-14 11:52
We're aware of it, and it is indeed a duplicate of #36 :/

**Closed by philpl** 2017-07-14 11:52 UTC
