### ISSUE TITLE
Scrolling broken in docs

### ISSUE THREAD

**Issue by johannesnagl** [styled-components/styled-components-website#89] opened 2017-08-29 09:23 UTC
Hi guys,

stumpled upon the beautiful website today - love it! Unfortunately, there's a nasty bug - at least in Mac OS, Chrome Version 60.0.3112.101 (Official Build) (64-bit):

If you scroll down the content completely, you can't scroll in the nav section anymore.

I've created a screencast to highlight this problem:

![screencast](http://g.recordit.co/YLWvWeXwrZ.gif)

Unfortunately, you can't see when I'm using my scroll wheel on the mouse - but it should be straight forward to reproduce the issue on your machine:

1. open up https://www.styled-components.com/docs
2. scroll the content area once
3. try to scroll the navigation area 
4. 💥 - nothing happens

If you select so much text in the navigation area that it's start scrolling based on your selection, it's free again and it's able to scroll the section. Until: You scroll the content once again! :)

**Comment by mxstbr** [comment] 2017-08-29 09:53
Can replicate that, annoying! PRs appreciated 😊

**Comment by valstu** [comment] 2017-08-29 11:17
I think this is "it's not a bug, it's a feature" kind of thing. If you scroll the content area and immediately scroll the navigation area it scrolls the main area. You cannot scroll the navigation area until the scrollbar on content area has disappeared. So the main area is still active while you try to scroll the navigation. If you wait it's all good.

https://file-cjyghmgjbe.now.sh/bug-demo-scs.m4v

**Comment by johannesnagl** [comment] 2017-08-29 11:19
> So the main area is still active while you try to scroll the navigation. If you wait it's all good.

you're absolutely right - haven't noticed this effect! nevertheless, this feels way more as a bug then as a feature :)

**Comment by mxstbr** [comment] 2017-08-29 11:35
Yeah this certainly isn't optimal :confused:

I'm hoping we can land #83 soon which should remove the scroll area from the sidebar (hopefully), so I'm going to close this issue for now since that _should_ fix it! Thanks for the report, that should not be a thing anymore sooooon

**Closed by mxstbr** 2017-08-29 11:35 UTC
Labels: bug, good first task
